# Generated by Django 3.1.4 on 2020-12-31 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exfd',
            name='collegename',
        ),
        migrations.RemoveField(
            model_name='exfd',
            name='rollno',
        ),
    ]
